from objects.aaaa import insert_aaa_data
from objects.aa import generate_airline_airfleet
from objects.route import insert_routes
from objects.flight import generate_flights
from objects.schedule import generate_flight_schedules
from objects.seat_layout import generate_seat_layout
from objects.flight_class import generate_flight_class
from objects.baggage_pricing import generate_baggage_pricing
from objects.passenger import generate_passengers
from objects.flight_crew import insert_flight_crew, generate_flight_flight_crew
from objects.checkin_agent import generate_checkin_agents

