from documentary.scheduled_flight import generate_scheduled_flights
from documentary.flight_price import generate_flight_prices
from documentary.booking import generate_bookings
from documentary.passenger_document import generate_passenger_documents
from documentary.booking_item import generate_booking_items
from documentary.booking_update import update_bookings
from documentary.payment import generate_payments
from documentary.flight_operation import generate_flight_operations
from documentary.flightcrew_flightoperation import generate_flight_crew_operations
from documentary.checkinagent_flightoperations import generate_checkin_agent_operations
from documentary.boarding_pass import generate_boarding_passes

